apiVersion: v2
name: dashboard-common-chart
description: Krateo PlatformOps Dashboard Common Chart
type: application
icon: "https://github.com/krateoplatformops/community/blob/main/logos/black/icon.svg"

version: 1.0.0
appVersion: 1.0.0

maintainers:
  - name: Mauro Sala
    email: mauro.sala@kiratech.it
    url: https://krateo.io
  - name: Luca Sepe
    email: luca.sepe@kiratech.it
    url: https://www.kiratech.it
