mongodb:
  uri: ""
  password: ""

services:
  ignore_self_signed_ssl: false
  hosts:
    auth: "http://auth-service.krateo-system.svc"
    deployment: "http://deployment-service.krateo-system.svc"
    template: "http://template-service.krateo-system.svc"
    endpoint: "http://endpoint-service.krateo-system.svc"
    git: "http://git-service.krateo-system.svc"
    argocd: "http://argocd-service.krateo-system.svc"
    log: "http://log-service.krateo-system.svc"
    socket: "http://socket-service.krateo-system.svc"
    kubernetes: "http://kubernetes-service.krateo-system.svc"
    keptn: "http://keptn-service.krateo-system.svc"
    codequality: "http://codequality-service.krateo-system.svc"
    pipeline: "http://pipeline-service.krateo-system.svc"
    secret: "http://secret-service.krateo-system.svc"
    provider: "http://provider-service.krateo-system.svc"
    capi: "http://capi-service.krateo-system.svc"
