ignore_self_signed_ssl: false

jwt:
  secret: "3b0a17f21dd243bdab165245ab2464f6"
  issuer: "13b46593fe704c57966ff41dca9dc48b"

title: Krateo PlatformOps

platform: kubernetes

schema: https
domain:
  # port: 8443
  base: krateo.site
  app: app
  api: api

cookie:
  name: "krateoplatformops"
  httpOnly: "true"
  secure: "true"
  maxAge: 2592000
  sameSite: "Strict"
  path: "/"

app:
  ingress:
    # Set host when it's required to have a different one than the host defined in domain stanza
    host: override.app.ingress.host
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

api:
  ingress:
    # Set host when it's required to have a different one than the host defined in domain stanza
    # host: override.api.ingress.host
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
