{{- $myVariable := "" }}
{{- if .Values.domain.port }}
  {{- $stringValue := toString .Values.domain.port }}
  {{- $myVariable = printf ":%s" $stringValue }}
{{- end }}
# You can now use the $myVariable in your template
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Release.Namespace }}
data:
  runtime-config.js: |
    window['runConfig'] = {
      apiBaseUrl: '{{ .Values.schema }}://{{ .Values.domain.api }}.{{ .Values.domain.base }}{{ $myVariable }}',
      notificationUrl: '{{ .Values.schema }}://{{ .Values.domain.api }}.{{ .Values.domain.base }}{{ $myVariable }}',
      title: '{{ .Values.title }}'
    }
