apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: krateo-consumer
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "kong"
username: "krateo-consumer"
credentials:
  - krateo-consumer-secret
