apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: krateo-consumer-secret
  namespace: {{ .Release.Namespace }}
data:
  key: {{ .Values.jwt.issuer | b64enc }}
  secret: {{ .Values.jwt.secret | b64enc }}
  kongCredType: and0