apiVersion: v1
kind: Secret
metadata:
  name: krateo-secret
data:
  JWT_SECRET: {{ .Values.jwt.secret | b64enc }}
  JWT_ISSUER: {{ .Values.jwt.issuer | b64enc }}
  {{ if .Values.mongodb.uri }}
  MONGODB_URI: {{ .Values.mongodb.uri | b64enc }}
  {{ end }}