apiVersion: v1
kind: ConfigMap
metadata:
  name: krateo-uri-config
data:
  AUTH_URI: {{ .Values.services.hosts.auth | quote }}
  DEPLOYMENT_URI: {{ .Values.services.hosts.deployment | quote }}
  TEMPLATE_URI: {{ .Values.services.hosts.template | quote }}
  ENDPOINT_URI: {{ .Values.services.hosts.endpoint | quote }}
  GIT_URI:  {{ .Values.services.hosts.git | quote }}
  ARGOCD_URI: {{ .Values.services.hosts.argocd | quote }}
  LOG_URI: {{ .Values.services.hosts.log | quote }}
  SOCKET_URI: {{ .Values.services.hosts.socket | quote }}
  BRIDGE_URI: {{ .Values.services.hosts.bridge | quote }}
  KUBERNETES_URI: {{ .Values.services.hosts.kubernetes | quote }}
  KEPTN_URI: {{ .Values.services.hosts.keptn | quote }}
  NAMESPACE: {{ .Release.Namespace | quote }}
