apiVersion: v1
kind: ConfigMap
metadata:
  name: krateo-uri-config
data:
  NAMESPACE: {{ .Release.Namespace | quote }}
  AUTH_URI: {{ .Values.services.hosts.auth | quote }}
  DEPLOYMENT_URI: {{ .Values.services.hosts.deployment | quote }}
  TEMPLATE_URI: {{ .Values.services.hosts.template | quote }}
  ENDPOINT_URI: {{ .Values.services.hosts.endpoint | quote }}
  GIT_URI: {{ .Values.services.hosts.git | quote }}
  ARGOCD_URI: {{ .Values.services.hosts.argocd | quote }}
  LOG_URI: {{ .Values.services.hosts.log | quote }}
  SOCKET_URI: {{ .Values.services.hosts.socket | quote }}
  SECRET_URI: {{ .Values.services.hosts.secret | quote }}
  PROVIDER_URI: {{ .Values.services.hosts.provider | quote }}
  {{ include "krateo.kubernetes" . }}
  {{ include "krateo.pipeline" . }}
  {{ include "krateo.keptn" . }}
  {{ include "krateo.codequality" . }}
  {{ include "krateo.nodetlsreject" . }}